name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: docker pull lanni0619/node-webapp:latest
      - name: Delete old docker container
        run: docker rm -f node-webapp-container || true
      - name: Run Docker Container
        run: docker run -d -p 80:3000 --name node-webapp-container lanni0619/node-webapp
